### ISSUE TITLE
Issue with the syling of the Feature Speakers section

### ISSUE THREAD

**Issue by AliRezaBmeDu** [AliRezaBmeDu/conference-capstone#2]
Hello mates, My feature speakers section in the capstone [project](https://github.com/AliRezaBmeDu/conference-capstone/pull/1) is breaking while the screen size varies. Please drop a suggestion if you might. Thank you!

**Comment by MayPyone** [comment]
For the speaker section, it might be better if the width of the image is set up using percent.

**Comment by Uzair-Manzoor** [comment]
hi @AliRezaBmeDu, in this case I would suggest to try getting some solution using chat gpt. I might be helpful in this case but not sure

**Comment by ngalamac** [comment]
- One thing you can also consider is to use grid features to style your card. This will easily make your section responsive to various screen sized when you use media queries. And also as earlier suggested you can use percentage units for width instead of fixed units like pixels
